In [37]:
import pandas as pd
import os

In [31]:
df = pd.read_csv("../data/raw/Gaming_Academic_Performance.csv")

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        8000 non-null   int64
 1   age               8000 non-null   int64
 2   gender            8000 non-null   object
 3   gaming_hours      8000 non-null   float64
 4   study_hours       8000 non-null   float64
 5   sleep_hours       8000 non-null   float64
 6   attendance        8000 non-null   float64
 7   gaming_genre      8000 non-null   object
 8   social_activity   8000 non-null   float64
 9   device_usage      8000 non-null   float64
 10  reaction_time_ms  8000 non-null   float64
 11  addiction_score   8000 non-null   float64
 12  stress_level      8000 non-null   object
 13  grades            8000 non-null   float64
dtypes: float64(9), int64(2), object(3)
memory usage: 875.1+ KB

    Features Included:
    Gaming hours, study hours, sleep hours
    Reaction time (cognitive performance)
    Stress levels
    Attendance and device usage
    Academic grades (target variable)

In [33]:
df.sample(10)

,student_id,age,gender,gaming_hours,study_hours,sleep_hours,attendance,gaming_genre,social_activity,device_usage,reaction_time_ms,addiction_score,stress_level,grades
6424,6425,22,Male,4.35,7.84,7.02,67.81,FPS,4.08,8.94,266.86,11.66,Medium,86.120000
3400,3401,19,Male,7.21,3.55,7.45,79.56,Casual,1.16,11.73,221.29,17.25,Low,39.100000
1395,1396,23,Female,2.81,8.23,7.80,78.49,FPS,2.97,5.22,277.67,4.92,Medium,100.000000
7337,7338,24,Female,6.00,6.39,5.02,93.78,FPS,3.57,8.81,241.26,14.53,Low,55.160000
4901,4902,20,Female,2.56,9.32,7.87,67.30,FPS,2.71,8.53,299.96,8.01,Medium,99.050000
4141,4142,18,Female,3.71,3.13,4.81,98.55,FPS,3.14,7.77,268.35,10.22,Medium,57.980000
2440,2441,21,Female,3.15,9.09,7.70,86.45,FPS,4.84,5.42,289.44,6.67,Medium,100.000000
3129,3130,23,Male,2.87,6.49,5.97,64.55,Casual,0.03,5.68,292.07,6.43,Medium,70.390000
1167,1168,22,Male,5.08,4.31,5.82,61.48,Casual,4.17,8.49,250.76,15.58,Low,44.580000
7649,7650,21,Female,7.34,1.04,4.61,67.23,RPG,1.90,9.54,230.13,13.39,Low,6.522582

## **Handling Missing Values**

In [34]:
df.isnull().sum()

student_id          0
age                 0
gender              0
gaming_hours        0
study_hours         0
sleep_hours         0
attendance          0
gaming_genre        0
social_activity     0
device_usage        0
reaction_time_ms    0
addiction_score     0
stress_level        0
grades              0
dtype: int64

    There is no any missing values in any columns

## **Encoding**

    There are 2 columns that can be encoded with one-hot encoding and a column with ordinal encoding

In [35]:
one_hot_columns = ["gender", "gaming_genre"]

for col in df[one_hot_columns]:
    dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
    df = pd.concat([df.drop(columns=[col]), dummies], axis=1)


stress_level_mapping = {
    "Low" : 0,
    "Medium" : 1,
    "High" : 2
}

df["stress_level"] = df["stress_level"].map(stress_level_mapping)

In [36]:
df.sample(10)

,student_id,age,gaming_hours,study_hours,sleep_hours,attendance,social_activity,device_usage,reaction_time_ms,addiction_score,stress_level,grades,gender_Female,gender_Male,gender_Other,gaming_genre_Casual,gaming_genre_FPS,gaming_genre_RPG
6628,6629,16,0.22,7.07,6.80,95.77,4.17,5.25,340.80,-0.33,1,92.030000,0,1,0,1,0,0
1357,1358,17,1.90,7.19,5.43,95.00,2.11,6.03,279.59,7.18,2,91.090000,0,1,0,0,0,1
5885,5886,16,2.51,8.32,5.50,74.14,0.33,5.61,277.82,5.86,2,88.100000,1,0,0,0,0,1
2355,2356,20,0.15,6.07,4.67,86.16,2.09,4.96,308.36,4.61,1,85.800000,1,0,0,1,0,0
7160,7161,19,4.92,1.95,4.31,72.48,4.17,7.18,260.28,10.55,1,21.490000,0,1,0,1,0,0
3853,3854,21,1.36,2.93,8.76,73.23,0.96,6.76,300.76,3.53,1,77.830000,0,1,0,0,0,1
4428,4429,20,7.41,7.46,5.30,72.22,4.74,11.66,216.80,15.94,2,53.290691,1,0,0,0,1,0
7727,7728,22,0.79,4.68,7.44,80.74,3.15,6.54,317.78,3.03,1,68.600000,0,1,0,0,0,1
6034,6035,22,3.15,2.38,5.77,87.59,3.02,6.80,294.98,8.89,1,61.390000,1,0,0,0,0,1
139,140,20,4.14,1.87,4.84,88.41,0.91,7.86,271.80,9.69,1,36.370000,1,0,0,0,1,0

    Encoded dataset is needed to be saved to a separate folder

In [38]:
output_folder = "../data/preprocessed"
os.makedirs(output_folder, exist_ok=True)
output_path = os.path.join(output_folder, "encoded_df.csv")
df.to_csv(output_path, index=False)

## **Model selection**

    There algorithms that require scaling and there also are algorithms that do not require scaling.

    Requires scaling!!!

    Linear Regression 
    Ridge Regression 
    Lasso Regression 
    SVM 

    Do not require scaling 

    Decision tree
    Random Forest