In [30]:
import pandas as pd

In [31]:
df = pd.read_csv('credit_card_frauds.csv')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339607 entries, 0 to 339606
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  339607 non-null  object
 1   merchant               339607 non-null  object
 2   category               339607 non-null  object
 3   amt                    339607 non-null  float64
 4   city                   339607 non-null  object
 5   state                  339607 non-null  object
 6   lat                    339607 non-null  float64
 7   long                   339607 non-null  float64
 8   city_pop               339607 non-null  int64
 9   job                    339607 non-null  object
 10  dob                    339607 non-null  object
 11  trans_num              339607 non-null  object
 12  merch_lat              339607 non-null  float64
 13  merch_long             339607 non-null  float64
 14  is_fraud               339607 non-null  int64
dtypes: float64(5), int64(2), object(8)
memory usage: 38.9+ MB

In [33]:
df.sample(10)

,trans_date_trans_time,merchant,category,amt,city,state,lat,long,city_pop,job,dob,trans_num,merch_lat,merch_long,is_fraud
334477,2020-12-26 00:56:28,DuBuque LLC,grocery_pos,79.72,Indian Wells,CA,33.7163,-116.3381,4677,Learning mentor,1955-05-06,3f30d74c76994640080547f99bb62249,33.734095,-115.544906,0
121331,2019-10-07 16:46:45,"Hahn, Bahringer and McLaughlin",personal_care,75.71,Fiddletown,CA,38.5234,-120.6763,832,Immigration officer,1987-05-19,a2ffeebd3ec5ba4d88df7cb7ae1e7b20,37.912283,-121.600214,0
2758,2019-01-09 08:40:21,Beier LLC,entertainment,52.17,Saint Louis,MO,38.6171,-90.4504,927396,Occupational hygienist,1960-03-12,a2c9c6ad424b86c46a547e967131019a,37.975060,-89.768907,0
192135,2020-03-09 23:31:54,"Cremin, Hamill and Reichel",misc_pos,989.31,Wendel,CA,40.3406,-120.2824,104,"Teacher, adult education",1989-08-16,fcef2cc7c49758cdef122cd68c38d858,40.230805,-119.635539,0
294650,2020-10-17 12:21:13,"Pouros, Walker and Spence",kids_pets,85.24,Centerview,MO,38.7897,-93.8702,2368,Electronics engineer,1989-07-17,b73f4f3385d63284cff728d0ba5cd723,38.672315,-94.175519,0
130462,2019-10-29 18:33:29,McDermott-Rice,misc_pos,3.87,Paauilo,HI,20.0271,-155.3697,1490,"Scientist, research (maths)",1991-04-13,821e37632beb07a536bc5a41ffa1c653,20.420332,-155.336499,0
194499,2020-03-16 01:51:36,Torp-Labadie,gas_transport,54.64,Hatch,UT,37.7175,-112.4777,258,Geoscientist,1961-11-24,316ce7ff2eb901b34fd681883e7b07f2,37.222756,-111.734027,0
322670,2020-12-11 18:27:55,"Windler, Goodwin and Kovacek",home,11.88,Mesa,ID,44.6255,-116.4493,129,Cartographer,1965-12-15,7c859d9e5518a66ec4d3a79f0cd966d0,44.443507,-115.728385,0
40834,2019-04-22 10:10:58,Smith-Stokes,misc_pos,41.31,Fort Washakie,WY,43.0048,-108.8964,1645,Freight forwarder,1976-02-26,a2376d0b23fe5ba3fd68f146dcc8a3f3,42.488254,-108.172714,0
127075,2019-10-21 17:34:14,"Douglas, Schneider and Turne",shopping_pos,2.64,Rocky Mount,MO,38.2911,-92.7059,1847,Tax inspector,1988-10-26,3f25a6d7d8bc3f8972cd45371c15a4ac,39.065366,-93.170428,0

In [34]:
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])
df['dob'] = pd.to_datetime(df['dob'], format="%Y-%m-%d")

## **Encoding**

In [38]:
from sklearn.preprocessing import LabelEncoder

def encoding(df):
    encoder = LabelEncoder()
    for col in df.columns:
        if df[col].dtype == "object":
            if df[col].nunique() <= 5:
                dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                df = pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col] = encoder.fit_transform(df[col])
    return df

In [39]:
df = encoding(df)

In [40]:
df.sample(10)

,trans_date_trans_time,merchant,category,amt,city,state,lat,long,city_pop,job,dob,trans_num,merch_lat,merch_long,is_fraud
73846,2019-07-01 12:50:47,102,5,27.04,48,9,43.7857,-124.1437,260,55,1956-09-01,285901,44.064816,-123.940365,0
238384,2020-06-22 12:12:28,536,11,7.08,116,11,48.8878,-118.2105,149,139,1978-06-21,249745,49.387602,-118.089042,0
26881,2019-03-20 04:30:43,43,2,46.37,133,6,37.3272,-91.0243,241,81,1974-10-27,150038,37.847236,-91.265790,0
16099,2019-02-21 03:54:50,521,9,29.38,65,6,39.1412,-94.3515,123373,57,1992-11-27,320552,38.689732,-93.653628,0
58409,2019-06-02 02:01:13,241,4,49.47,37,8,35.7206,-108.0271,5662,74,1989-04-08,7126,36.529287,-107.928479,0
318288,2020-12-06 16:33:28,334,1,39.31,21,11,48.4786,-122.3345,14871,119,1974-03-10,27713,48.002971,-123.304271,0
143806,2019-11-30 17:45:19,69,6,23.73,58,7,41.6414,-96.5232,1745,49,1973-12-26,156826,41.417027,-97.340787,0
196931,2020-03-21 19:25:13,159,10,42.90,105,6,40.1362,-95.2138,1631,7,1953-01-20,69626,40.304052,-94.884849,0
95278,2019-08-12 02:20:11,580,9,53.11,82,2,39.0470,-122.9328,11256,114,1972-10-18,62687,38.698182,-123.637315,0
80185,2019-07-14 04:32:04,147,4,130.39,23,7,40.2967,-98.7370,493,141,1940-09-13,146777,41.142714,-99.362893,0

## **Scaling**

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339607 entries, 0 to 339606
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  339607 non-null  datetime64[ns]
 1   merchant               339607 non-null  int32
 2   category               339607 non-null  int32
 3   amt                    339607 non-null  float64
 4   city                   339607 non-null  int32
 5   state                  339607 non-null  int32
 6   lat                    339607 non-null  float64
 7   long                   339607 non-null  float64
 8   city_pop               339607 non-null  int64
 9   job                    339607 non-null  int32
 10  dob                    339607 non-null  datetime64[ns]
 11  trans_num              339607 non-null  int32
 12  merch_lat              339607 non-null  float64
 13  merch_long             339607 non-null  float64
 14  is_fraud               339607 non-null  int64
dtypes: datetime64[ns](2), float64(5), int32(6), int64(2)
memory usage: 31.1 MB

In [42]:
from sklearn.preprocessing import MinMaxScaler

def scaling(df):
    scaler = MinMaxScaler()
    num_cols = df.select_dtypes(include=['int64', 'int32', 'float64']).columns.drop('is_fraud')
    df[num_cols] = scaler.fit_transform(df[num_cols])
    return df

In [43]:
df = scaling(df)

In [51]:
df.sample(10)

,trans_date_trans_time,merchant,category,amt,city,state,lat,long,city_pop,job,dob,trans_num,merch_lat,merch_long,is_fraud
13166,2019-02-11 19:36:42,0.403179,0.461538,0.001128,0.994286,0.833333,0.447011,0.707089,0.005846,0.487654,1979-08-14,0.802763,0.460605,0.713855,0
263641,2020-08-09 18:51:15,0.257225,0.000000,0.003919,0.491429,0.666667,0.345464,0.789120,0.000084,0.049383,1961-10-24,0.891283,0.367659,0.777985,0
164749,2019-12-25 21:08:50,0.200867,0.000000,0.002465,0.308571,0.166667,0.352977,0.599376,0.000032,0.253086,1973-02-07,0.617860,0.376574,0.597749,0
203860,2020-04-06 23:54:51,0.320809,0.692308,0.000474,0.468571,0.166667,0.407573,0.562039,0.004702,0.703704,1972-10-18,0.622404,0.432115,0.567321,0
185056,2020-02-18 09:32:19,0.767341,0.923077,0.000203,0.074286,0.166667,0.423981,0.592184,0.000704,0.117284,1967-05-27,0.725170,0.447514,0.594110,0
190982,2020-03-07 19:40:52,0.176301,0.538462,0.005033,0.097143,0.250000,0.425539,0.796364,0.038715,0.333333,1967-10-18,0.971982,0.441469,0.785165,0
172368,2020-01-08 18:55:24,0.914740,1.000000,0.000289,0.908571,0.166667,0.390338,0.562280,0.000122,0.660494,1954-07-05,0.232537,0.383974,0.571395,0
253637,2020-07-21 06:16:10,0.124277,0.307692,0.003147,0.148571,0.583333,0.476788,0.900532,0.000218,0.592593,1975-01-26,0.463623,0.462025,0.894768,0
289455,2020-10-04 19:19:20,0.456647,0.076923,0.001317,0.771429,1.000000,0.462410,0.742236,0.011714,0.611111,1984-08-01,0.802486,0.459405,0.743078,0
322188,2020-12-11 01:23:31,0.813584,0.307692,0.004030,0.525714,0.500000,0.438562,0.970247,0.000198,0.975309,1966-02-13,0.020703,0.437179,0.955546,0

    Deleting datetime columns

In [60]:
df = df.drop(columns=["trans_date_trans_time", "dob"])

## **Logistic Regression**

In [70]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

In [71]:
x = df.drop("is_fraud", axis=1)
y = df["is_fraud"]

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

lr = LogisticRegression()
lr.fit(x_train, y_train)

y_pred = lr.predict(x_test)
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     67555
           1       0.00      0.00      0.00       367

    accuracy                           0.99     67922
   macro avg       0.50      0.50      0.50     67922
weighted avg       0.99      0.99      0.99     67922

## **Cross Validation**

In [78]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(lr, x,y, cv=cv)
print(scores)

[0.99467036 0.99474397 0.99475862 0.99474389 0.99465556]

## **Decision Tree Classifier**

In [72]:
from sklearn.tree import DecisionTreeClassifier

In [75]:
dtc =DecisionTreeClassifier()
dtc.fit(x_train, y_train)

y_pred = dtc.predict(x_test)

cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     67555
           1       0.58      0.59      0.59       367

    accuracy                           1.00     67922
   macro avg       0.79      0.79      0.79     67922
weighted avg       1.00      1.00      1.00     67922

## **Cross Validation**

In [77]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(dtc, x,y, cv=cv)
print(scores)

[0.99570095 0.99575984 0.99573033 0.99549477 0.99559783]