#### Lesson 8. Scaling

In [138]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, LabelEncoder

In [139]:
df = pd.read_csv("PoliceKillingsUS.csv", encoding="latin1")
df

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
0,3,Tim Elliot,02/01/15,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False
1,4,Lewis Lee Lembke,02/01/15,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False
2,5,John Paul Quintero,03/01/15,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False
3,8,Matthew Hoffman,04/01/15,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False
4,9,Michael Rodriguez,04/01/15,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2530,2822,Rodney E. Jacobs,28/07/17,shot,gun,31.0,M,NaN,Kansas City,MO,False,attack,Not fleeing,False
2531,2813,TK TK,28/07/17,shot,vehicle,NaN,M,NaN,Albuquerque,NM,False,attack,Car,False
2532,2818,Dennis W. Robinson,29/07/17,shot,gun,48.0,M,NaN,Melba,ID,False,attack,Car,False
2533,2817,Isaiah Tucker,31/07/17,shot,vehicle,28.0,M,B,Oshkosh,WI,False,attack,Car,True
2534,2815,Dwayne Jeune,31/07/17,shot,knife,32.0,M,B,Brooklyn,NY,True,attack,Not fleeing,False

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2535 entries, 0 to 2534
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       2535 non-null   int64
 1   name                     2535 non-null   object
 2   date                     2535 non-null   object
 3   manner_of_death          2535 non-null   object
 4   armed                    2526 non-null   object
 5   age                      2458 non-null   float64
 6   gender                   2535 non-null   object
 7   race                     2340 non-null   object
 8   city                     2535 non-null   object
 9   state                    2535 non-null   object
 10  signs_of_mental_illness  2535 non-null   bool
 11  threat_level             2535 non-null   object
 12  flee                     2470 non-null   object
 13  body_camera              2535 non-null   bool
dtypes: bool(2), float64(1), int64(1), object(10)
memory usage: 242.7+ KB

In [141]:
df.isnull().sum()

id                           0
name                         0
date                         0
manner_of_death              0
armed                        9
age                         77
gender                       0
race                       195
city                         0
state                        0
signs_of_mental_illness      0
threat_level                 0
flee                        65
body_camera                  0
dtype: int64

In [142]:
df.columns

Index(['id', 'name', 'date', 'manner_of_death', 'armed', 'age', 'gender',
       'race', 'city', 'state', 'signs_of_mental_illness', 'threat_level',
       'flee', 'body_camera'],
      dtype='object')

#### Handling missing values.

In [143]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype != "object":
            df[col].fillna(df[col].mean(), inplace=True)
        elif df[col].dtype == "object":
            df[col].fillna(df[col].mode()[0], inplace=True)

In [144]:
df.isnull().sum()

id                         0
name                       0
date                       0
manner_of_death            0
armed                      0
age                        0
gender                     0
race                       0
city                       0
state                      0
signs_of_mental_illness    0
threat_level               0
flee                       0
body_camera                0
dtype: int64

#### Encoding with for loop (One-hot and Label Encoding)

In [145]:
encoder = LabelEncoder()
encoder

LabelEncoder()

In [146]:
for col in df.columns:
    if df[col].dtype == 'object':
        if df[col].nunique() <= 5:
            dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
            df = pd.concat([df.drop(columns=col), dummies], axis=1)
        elif df[col].dtype == "bool":
            df[col] = encoder.fit_transform(df[col])
        else:
            df[col] = encoder.fit_transform(df[col])

In [147]:
df.sample(5)

,id,name,date,armed,age,race,city,state,signs_of_mental_illness,body_camera,...,manner_of_death_shot and Tasered,gender_F,gender_M,threat_level_attack,threat_level_other,threat_level_undetermined,flee_Car,flee_Foot,flee_Not fleeing,flee_Other
803,947,1376,682,25,34.0,2,557,4,False,False,...,0,0,1,1,0,0,0,0,1,0
112,150,1512,401,64,25.0,1,810,9,True,False,...,1,0,1,0,1,0,0,0,1,0
234,316,1799,754,25,40.0,5,1349,19,False,False,...,0,0,1,1,0,0,0,1,0,0
8,16,169,143,64,34.0,5,174,12,False,True,...,0,1,0,0,1,0,0,0,1,0
210,230,227,521,25,31.0,5,814,13,False,True,...,0,0,1,1,0,0,0,0,1,0

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2535 entries, 0 to 2534
Data columns (total 21 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                2535 non-null   int64
 1   name                              2535 non-null   int32
 2   date                              2535 non-null   int32
 3   armed                             2535 non-null   int32
 4   age                               2535 non-null   float64
 5   race                              2535 non-null   int32
 6   city                              2535 non-null   int32
 7   state                             2535 non-null   int32
 8   signs_of_mental_illness           2535 non-null   bool
 9   body_camera                       2535 non-null   bool
 10  manner_of_death_shot              2535 non-null   int32
 11  manner_of_death_shot and Tasered  2535 non-null   int32
 12  gender_F                          2535 non-null   int32
 13  gender_M                          2535 non-null   int32
 14  threat_level_attack               2535 non-null   int32
 15  threat_level_other                2535 non-null   int32
 16  threat_level_undetermined         2535 non-null   int32
 17  flee_Car                          2535 non-null   int32
 18  flee_Foot                         2535 non-null   int32
 19  flee_Not fleeing                  2535 non-null   int32
 20  flee_Other                        2535 non-null   int32
dtypes: bool(2), float64(1), int32(17), int64(1)
memory usage: 213.0 KB

#### Scaling with for loop

In [149]:
scaler = StandardScaler()
scaler

StandardScaler()

In [150]:
num_col=df.select_dtypes(include=['int64','float64', 'int32']).columns.drop(['signs_of_mental_illness', 'body_camera'], errors = 'ignore') # Target qiymat scaling qilinmaydi.

In [151]:
for col in df.columns:
    df[col] = scaler.fit_transform(df[[col]])

In [152]:
df.sample(5)

,id,name,date,armed,age,race,city,state,signs_of_mental_illness,body_camera,...,manner_of_death_shot and Tasered,gender_F,gender_M,threat_level_attack,threat_level_other,threat_level_undetermined,flee_Car,flee_Foot,flee_Not fleeing,flee_Other
1692,0.572052,0.680342,0.393614,-0.615157,0.732312,0.871006,1.249772,1.315950,1.733418,2.890371,...,-0.269794,4.763569,-4.763569,0.757335,-0.658037,-0.257818,-0.423166,-0.362204,0.663582,-0.198395
2165,1.220583,-1.108258,-0.704167,-0.615157,0.264611,0.871006,-0.754525,-1.132925,1.733418,-0.345976,...,-0.269794,-0.209927,0.209927,0.757335,-0.658037,-0.257818,-0.423166,-0.362204,0.663582,-0.198395
1330,0.084710,-0.532807,-1.361233,1.726056,0.264611,0.871006,-1.314840,0.122908,-0.576895,-0.345976,...,-0.269794,-0.209927,0.209927,0.757335,-0.658037,-0.257818,-0.423166,-0.362204,0.663582,-0.198395
453,-1.097757,-0.005772,0.834329,-0.205445,-1.138489,0.871006,-0.268261,-0.379425,-0.576895,-0.345976,...,-0.269794,-0.209927,0.209927,0.757335,-0.658037,-0.257818,-0.423166,-0.362204,0.663582,-0.198395
764,-0.679675,-1.582728,-0.640063,1.784586,-0.125139,-0.774300,0.027941,-0.505008,-0.576895,-0.345976,...,3.706531,-0.209927,0.209927,-1.320419,-0.658037,3.878699,-0.423166,-0.362204,0.663582,-0.198395

In [153]:
scaler = MinMaxScaler()
scaler

MinMaxScaler()

In [154]:
for col in df.columns:
    df[col] = scaler.fit_transform(df[[col]])

In [155]:
df.sample(5)

,id,name,date,armed,age,race,city,state,signs_of_mental_illness,body_camera,...,manner_of_death_shot and Tasered,gender_F,gender_M,threat_level_attack,threat_level_other,threat_level_undetermined,flee_Car,flee_Foot,flee_Not fleeing,flee_Other
1952,0.772614,0.811290,1.000000,0.477612,0.470588,1.0,0.521893,0.18,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1284,0.520752,0.908065,0.464692,0.970149,0.235294,1.0,0.608051,0.30,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1048,0.425683,0.814516,0.818907,0.373134,0.576471,1.0,0.123588,0.74,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1151,0.467187,0.122581,0.788155,0.373134,0.376471,0.2,0.391949,0.32,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
753,0.316070,0.835081,0.157175,0.373134,0.517647,1.0,0.988701,0.62,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [156]:
scaler = RobustScaler()
scaler

RobustScaler()

In [157]:
for col in df.columns:
    df[col] = scaler.fit_transform(df[[col]])

In [158]:
df.sample(5)

,id,name,date,armed,age,race,city,state,signs_of_mental_illness,body_camera,...,manner_of_death_shot and Tasered,gender_F,gender_M,threat_level_attack,threat_level_other,threat_level_undetermined,flee_Car,flee_Foot,flee_Not fleeing,flee_Other
1230,-0.027982,-0.100475,0.535342,0.0,-0.722222,-1.00,-0.822285,0.12500,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
728,-0.435199,-0.103639,0.505214,0.0,-0.388889,-1.00,0.960508,-0.37500,1.0,0.0,...,0.0,0.0,0.0,-1.0,0.0,1.0,0.0,0.0,0.0,0.0
1799,0.409426,0.952532,-0.889919,0.0,1.333333,0.00,-0.183357,-0.06250,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
319,-0.762887,-0.167722,0.808806,0.0,-0.777778,-1.00,0.245416,-0.06250,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1738,0.360088,0.561709,-0.493627,0.5,-0.777778,-0.75,-0.407616,0.84375,1.0,0.0,...,0.0,0.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.0,0.0