In [61]:
y_actual = [3, 4.5, 5, 6, 7]
y_pred = [2.5, 4.0, 6.0, 5.5, 8.0]

In [120]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [69]:
r2=r2_score(y_actual,y_pred)
mse=mean_squared_error(y_actual,y_pred)
rmse=pow(mse,(1/2))
mae=mean_absolute_error(y_actual,y_pred)

In [70]:
print(r2)
print(mse)
print(rmse)
print(mae)

0.701086956521739
0.55
0.7416198487095663
0.7

In [97]:
import pandas as pd
df=pd.read_csv('income.csv')

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       16 non-null     object
 1   Age        21 non-null     float64
 2   Income($)  12 non-null     float64
dtypes: float64(2), object(1)
memory usage: 660.0+ bytes

In [74]:
df.isnull().sum()

Name          6
Age           1
Income($)    10
dtype: int64

In [98]:
# Function + Missing qiymatlar
def tozala(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [99]:
tozala(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       22 non-null     object
 1   Age        22 non-null     float64
 2   Income($)  22 non-null     float64
dtypes: float64(2), object(1)
memory usage: 660.0+ bytes

In [79]:
tozala(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 283901 entries, 0 to 283900
Data columns (total 46 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             283901 non-null  int64
 1   Lng                    283901 non-null  float64
 2   Lat                    283901 non-null  float64
 3   tradeTime              283901 non-null  float64
 4   followers              283901 non-null  float64
 5   totalPrice             283901 non-null  float64
 6   square                 283901 non-null  float64
 7   livingRoom             283901 non-null  float64
 8   drawingRoom            283901 non-null  float64
 9   kitchen                283901 non-null  float64
 10  bathRoom               283901 non-null  float64
 11  constructionTime       283901 non-null  float64
 12  ladderRatio            283901 non-null  float64
 13  fiveYearsProperty      283901 non-null  float64
 14  subway                 283901 non-null  float64
 15  communityAverage       283901 non-null  float64
 16  floor_height           283901 non-null  float64
 17  renovationCondition_2  283901 non-null  int64
 18  renovationCondition_3  283901 non-null  int64
 19  renovationCondition_4  283901 non-null  int64
 20  buildingStructure_2    283901 non-null  int64
 21  buildingStructure_3    283901 non-null  int64
 22  buildingStructure_4    283901 non-null  int64
 23  buildingStructure_5    283901 non-null  int64
 24  buildingStructure_6    283901 non-null  int64
 25  buildingType_2.0       283901 non-null  int64
 26  buildingType_3.0       283901 non-null  int64
 27  buildingType_4.0       283901 non-null  int64
 28  district_2             283901 non-null  int64
 29  district_3             283901 non-null  int64
 30  district_4             283901 non-null  int64
 31  district_5             283901 non-null  int64
 32  district_6             283901 non-null  int64
 33  district_7             283901 non-null  int64
 34  district_8             283901 non-null  int64
 35  district_9             283901 non-null  int64
 36  district_10            283901 non-null  int64
 37  district_11            283901 non-null  int64
 38  district_12            283901 non-null  int64
 39  district_13            283901 non-null  float64
 40  elevator_1.0           283901 non-null  float64
 41  floor_type_低           283901 non-null  float64
 42  floor_type_底           283901 non-null  float64
 43  floor_type_未知          283901 non-null  float64
 44  floor_type_顶           283901 non-null  float64
 45  floor_type_高           283901 non-null  float64
dtypes: float64(23), int64(23)
memory usage: 99.6 MB

In [84]:
df.isnull().sum()

Name         0
Age          0
Income($)    0
dtype: int64

In [ ]:
# import pandas as pd
# df=pd.read_csv('house_price.txt')

In [85]:
# df.isnull().sum()

In [86]:
from sklearn.preprocessing import LabelEncoder

In [100]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

def encodla(df):
    encoder = LabelEncoder()

    for col in df.columns.to_list(): 
        if df[col].dtype == 'object':
            if df[col].nunique() <= 6:
                dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                df.drop(columns=[col], inplace=True)
                df[dummies.columns] = dummies
            else:
                df[col] = encoder.fit_transform(df[col].astype(str))
    
    return df

In [101]:
df = encodla(df)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       22 non-null     int32
 1   Age        22 non-null     float64
 2   Income($)  22 non-null     float64
dtypes: float64(2), int32(1)
memory usage: 572.0 bytes

In [91]:
df.head()

   Name        Age  Income($)
0    12  35.190476    70000.0
1     7  29.000000    90000.0
2     8  29.000000    61000.0
3     4  28.000000   106000.0
4     6  42.000000   106000.0

In [52]:
from sklearn.preprocessing import MinMaxScaler

In [92]:
scaler=MinMaxScaler()

In [93]:
def scale_qil(df):
    for col in df.columns:
        if df[col].dtype!='object':
            df[col]=scaler.fit_transform(df[[col]])
    return df

In [94]:
df=scale_qil(df)

In [95]:
df.head()

       Name       Age  Income($)
0  0.800000  0.540616   0.213675
1  0.466667  0.176471   0.384615
2  0.533333  0.176471   0.136752
3  0.266667  0.117647   0.521368
4  0.400000  0.941176   0.521368

In [103]:
numerical_col=df.select_dtypes(include=['int32','float64']).columns.drop('Income($)')

In [104]:
numerical_col

Index(['Name', 'Age'], dtype='object')

In [105]:
df[numerical_col]=scaler.fit_transform(df[numerical_col])

In [106]:
df.head()

       Name       Age  Income($)
0  0.800000  0.540616    70000.0
1  0.466667  0.176471    90000.0
2  0.533333  0.176471    61000.0
3  0.266667  0.117647   106000.0
4  0.400000  0.941176   106000.0

In [108]:
x=df.drop('Income($)',axis=1)

In [109]:
y=df['Income($)']

In [112]:
from sklearn.model_selection import train_test_split

In [113]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression

In [115]:
lr=LinearRegression()

In [116]:
lr

LinearRegression()

In [117]:
lr.fit(x_train,y_train)

LinearRegression()

In [118]:
y_pred=lr.predict(x_test)

In [119]:
y_pred

array([ 88485.04873954,  83329.94725702, 116523.00655467,  81842.8812615 ,
        81675.92968083])

In [121]:
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=pow(mse,(1/2))
mae=mean_absolute_error(y_test,y_pred)

In [122]:
print(r2)
print(mse)
print(rmse)
print(mae)

0.24164190542024233
614452062.5523028
24788.14358826217
22622.656797105024