In [103]:
import pandas as pd
df=pd.read_csv('heart_cleveland_upload.csv')

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        297 non-null    int64
 1   gender     297 non-null    int64
 2   cp         297 non-null    int64
 3   trestbps   297 non-null    int64
 4   chol       297 non-null    int64
 5   fbs        297 non-null    int64
 6   restecg    297 non-null    int64
 7   thalach    297 non-null    int64
 8   exang      297 non-null    int64
 9   oldpeak    297 non-null    float64
 10  slope      297 non-null    int64
 11  ca         297 non-null    int64
 12  thal       297 non-null    int64
 13  condition  297 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 32.6 KB

# SVC

In [105]:
df.head()

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0

In [49]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('condition')
df[num_col]=scaler.fit_transform(df[num_col])

In [50]:
df.head()

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,0.833333,1.0,0.0,0.622642,0.246575,1.0,1.0,0.458015,0.0,0.016129,0.5,0.333333,0.0,0
1,0.833333,0.0,0.0,0.433962,0.257991,0.0,0.0,0.610687,0.0,0.290323,0.0,0.666667,0.0,0
2,0.770833,0.0,0.0,0.528302,0.228311,0.0,0.0,0.328244,0.0,0.419355,1.0,0.000000,0.0,0
3,0.750000,1.0,0.0,0.415094,0.356164,1.0,1.0,0.786260,0.0,0.225806,0.5,0.333333,0.0,1
4,0.729167,1.0,0.0,0.150943,0.194064,0.0,1.0,0.557252,1.0,0.290323,0.5,0.000000,0.0,0

In [106]:
from sklearn.model_selection import train_test_split

In [107]:
x=df.drop('condition',axis=1)

In [108]:
y=df['condition']

In [109]:
x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [110]:
from sklearn.svm import SVC, SVR

In [111]:
svc=SVC(kernel='linear',C=1.0)

In [112]:
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [113]:
y_pred=svc.predict(x_test)

In [114]:
y_pred

array([1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0], dtype=int64)

In [115]:
from sklearn.metrics import classification_report

In [124]:
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.79      0.72      0.75        32
           1       0.71      0.79      0.75        28

    accuracy                           0.75        60
   macro avg       0.75      0.75      0.75        60
weighted avg       0.75      0.75      0.75        60

In [118]:
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.79      0.72      0.75        32
           1       0.71      0.79      0.75        28

    accuracy                           0.75        60
   macro avg       0.75      0.75      0.75        60
weighted avg       0.75      0.75      0.75        60

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        297 non-null    int64
 1   gender     297 non-null    int64
 2   cp         297 non-null    int64
 3   trestbps   297 non-null    int64
 4   chol       297 non-null    int64
 5   fbs        297 non-null    int64
 6   restecg    297 non-null    int64
 7   thalach    297 non-null    int64
 8   exang      297 non-null    int64
 9   oldpeak    297 non-null    float64
 10  slope      297 non-null    int64
 11  ca         297 non-null    int64
 12  thal       297 non-null    int64
 13  condition  297 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 32.6 KB

# SVR

In [120]:
df.head()

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0

In [121]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('chol')
df[num_col]=scaler.fit_transform(df[num_col])

In [122]:
df.head()

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,0.833333,1.0,0.0,0.622642,234,1.0,1.0,0.458015,0.0,0.016129,0.5,0.333333,0.0,0.0
1,0.833333,0.0,0.0,0.433962,239,0.0,0.0,0.610687,0.0,0.290323,0.0,0.666667,0.0,0.0
2,0.770833,0.0,0.0,0.528302,226,0.0,0.0,0.328244,0.0,0.419355,1.0,0.000000,0.0,0.0
3,0.750000,1.0,0.0,0.415094,282,1.0,1.0,0.786260,0.0,0.225806,0.5,0.333333,0.0,1.0
4,0.729167,1.0,0.0,0.150943,211,0.0,1.0,0.557252,1.0,0.290323,0.5,0.000000,0.0,0.0

In [125]:
svr=SVR(kernel='rbf',C=0.5)

In [126]:
svr

SVR(C=0.5)

In [127]:
svr.fit(x_train,y_train)

SVR(C=0.5)

In [128]:
y_pred=svr.predict(x_test)

In [129]:
y_pred

array([ 0.3934064 ,  0.19296817,  0.4737162 ,  0.0731731 ,  0.45646759,
        0.64725437,  0.71269083,  0.93260917,  0.65731373,  0.0619687 ,
        0.23189213,  0.42210913,  0.59548422,  0.28633545,  0.37904069,
        0.21475122,  0.65183687,  0.1377554 ,  0.67099437,  0.02559687,
        0.59254343,  0.22163822, -0.04491159,  0.25892478,  0.00284289,
        0.69720239,  0.57122467,  0.85769357,  0.5470928 ,  0.25767156,
        0.28591626,  0.5351397 ,  0.49314705,  0.50395493,  0.44474801,
        0.51337967,  0.41090022,  0.55632879,  0.42054668,  0.58450651,
        0.13046977,  0.26585154,  0.15524198,  0.13963143,  0.34283375,
        0.40100207,  0.33177791,  0.38427111,  0.78360991,  0.3646525 ,
        0.27204554,  0.42654383,  0.4223573 ,  0.23783677,  0.50201651,
        0.09651868,  0.57291915,  0.8986508 ,  0.4342431 ,  0.18562248])

In [130]:
from sklearn.metrics  import r2_score, mean_absolute_error

In [131]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)

In [132]:
print(r2)
print(mae)

-0.02159334871862173
0.4462306658132208

In [93]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)

In [94]:
print(r2)
print(mae)

0.2741308268075179
0.299021168692693

In [102]:
print(r2)
print(mae)

0.30436334894613315
0.29752277628070994

In [133]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

In [134]:
rfc=RandomForestClassifier()
rfr=RandomForestRegressor()

In [135]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [136]:
y_pred=rfc.predict(x_test)

In [137]:
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.76      0.69      0.72        32
           1       0.68      0.75      0.71        28

    accuracy                           0.72        60
   macro avg       0.72      0.72      0.72        60
weighted avg       0.72      0.72      0.72        60

In [138]:
rfr.fit(x_train,y_train)

RandomForestRegressor()

In [139]:
y_pred=rfr.predict(x_test)

In [140]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)

In [141]:
print(r2)
print(mae)

0.2805424107142859
0.31583333333333335