# Data preprocessing

In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('retail_store_sales.csv')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [10]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [11]:
df.sample(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
3886,TXN_1002182,CUST_01,Food,Item_5_FOOD,11.0,5.0,55.0,Digital Wallet,In-store,2024-10-08,True
4993,TXN_6829547,CUST_07,Food,Item_22_FOOD,36.5,8.0,292.0,Credit Card,Online,2023-09-02,NaN
5575,TXN_9556639,CUST_23,Computers and electric accessories,Item_5_CEA,11.0,7.0,77.0,Digital Wallet,Online,2023-04-29,NaN
2899,TXN_6887406,CUST_04,Milk Products,Item_17_MILK,29.0,8.0,232.0,Digital Wallet,Online,2022-03-23,False
11685,TXN_3462357,CUST_16,Food,Item_14_FOOD,24.5,8.0,196.0,Cash,In-store,2023-08-27,True
899,TXN_4285730,CUST_17,Patisserie,Item_24_PAT,39.5,6.0,237.0,Cash,Online,2022-01-14,NaN
5612,TXN_3668726,CUST_19,Electric household essentials,Item_16_EHE,27.5,5.0,137.5,Cash,Online,2022-05-14,True
8073,TXN_8573044,CUST_23,Beverages,NaN,NaN,8.0,280.0,Credit Card,In-store,2023-02-18,False
12325,TXN_1051037,CUST_14,Patisserie,Item_16_PAT,27.5,3.0,82.5,Credit Card,In-store,2023-06-14,False
7639,TXN_2964837,CUST_03,Beverages,Item_19_BEV,32.0,10.0,320.0,Cash,Online,2025-01-02,True

| Code             | Purpose                      | Works On           | Notes                             |
| ---------------- | ---------------------------- | ------------------ | --------------------------------- |
| `fillna(mean)`   | Replace missing with average | int, float         | Sensitive to outliers             |
| `fillna(mode)`   | Replace with most frequent   | object, int, float | Good for categories               |
| `fillna(median)` | Replace with middle value    | int, float         | Robust to outliers                |
| `fillna(value)`  | Replace with constant        | any                | Manual default fill               |
| `drop(axis=1)`   | Drop column                  | column name        | Removes unwanted or empty columns |
| `dropna()`       | Drop rows with missing       | entire row         | Use carefully on large datasets   |

# Mean

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [14]:
df['Price Per Unit'].fillna(df['Price Per Unit'].mean(), inplace=True)

C:\Users\mrcoo\AppData\Local\Temp\ipykernel_9204\3852671811.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price Per Unit'].fillna(df['Price Per Unit'].mean(), inplace=True)

In [16]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit         0
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

# Mode

In [17]:
df['Item'].fillna(df['Item'].mode()[0], inplace=True)

In [18]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                   0
Price Per Unit         0
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

# Median

In [19]:
df['Quantity'].fillna(df['Quantity'].median(), inplace=True)

C:\Users\mrcoo\AppData\Local\Temp\ipykernel_9204\487052630.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].fillna(df['Quantity'].median(), inplace=True)

In [20]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                   0
Price Per Unit         0
Quantity               0
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [21]:
df.sample(15)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
1393,TXN_8898496,CUST_08,Food,Item_4_FOOD,9.5,2.0,19.0,Credit Card,Online,2023-12-13,True
8189,TXN_8940025,CUST_11,Milk Products,Item_2_BEV,15.5,6.0,NaN,Credit Card,Online,2022-07-24,True
9670,TXN_5250994,CUST_03,Food,Item_13_FOOD,23.0,3.0,69.0,Credit Card,Online,2022-08-28,False
9453,TXN_9110626,CUST_25,Electric household essentials,Item_22_EHE,36.5,6.0,219.0,Cash,Online,2024-09-22,True
10680,TXN_1564693,CUST_13,Beverages,Item_17_BEV,29.0,6.0,174.0,Cash,In-store,2024-01-02,True
6061,TXN_6832658,CUST_09,Furniture,Item_6_FUR,12.5,2.0,25.0,Cash,Online,2023-10-10,NaN
6581,TXN_2012777,CUST_12,Furniture,Item_10_FUR,18.5,6.0,111.0,Cash,In-store,2023-04-05,True
9168,TXN_5169916,CUST_19,Beverages,Item_16_BEV,27.5,10.0,275.0,Credit Card,In-store,2023-10-14,False
1676,TXN_8950168,CUST_08,Computers and electric accessories,Item_5_CEA,11.0,4.0,44.0,Cash,Online,2024-08-17,True
4918,TXN_5487075,CUST_09,Patisserie,Item_12_PAT,21.5,1.0,21.5,Credit Card,Online,2022-08-14,NaN
5887,TXN_4337439,CUST_19,Patisserie,Item_13_PAT,23.0,9.0,207.0,Cash,Online,2023-05-15,True
3344,TXN_6376892,CUST_20,Furniture,Item_16_FUR,27.5,5.0,137.5,Credit Card,Online,2023-05-17,NaN
11903,TXN_4366890,CUST_04,Electric household essentials,Item_20_EHE,33.5,9.0,301.5,Credit Card,Online,2022-11-04,True
9876,TXN_9152328,CUST_06,Food,Item_13_FOOD,23.0,10.0,230.0,Digital Wallet,In-store,2022-03-30,False
2069,TXN_7015442,CUST_24,Computers and electric accessories,Item_5_CEA,11.0,7.0,77.0,Credit Card,Online,2024-06-06,NaN

# Fixed

In [24]:
mean = df['Total Spent'].mean()
df['Total Spent'].fillna(mean, inplace=True)

C:\Users\mrcoo\AppData\Local\Temp\ipykernel_9204\934173593.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Total Spent'].fillna(mean, inplace=True)

In [25]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                   0
Price Per Unit         0
Quantity               0
Total Spent            0
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

# Drop

In [26]:
df.drop('Discount Applied',axis=1,inplace=True)

In [27]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [30]:
df.sample(20)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date
8898,TXN_2818752,CUST_14,Patisserie,Item_8_PAT,15.500000,2.0,31.0,Digital Wallet,Online,2024-10-17
1092,TXN_6619000,CUST_16,Furniture,Item_12_FUR,21.500000,10.0,215.0,Cash,Online,2024-05-02
6824,TXN_7737340,CUST_22,Computers and electric accessories,Item_20_CEA,33.500000,10.0,335.0,Credit Card,Online,2024-07-31
7828,TXN_5113509,CUST_02,Furniture,Item_24_FUR,39.500000,9.0,355.5,Cash,In-store,2022-07-21
8935,TXN_2868734,CUST_17,Furniture,Item_6_FUR,12.500000,6.0,75.0,Credit Card,Online,2022-05-13
8003,TXN_9361358,CUST_13,Food,Item_2_BEV,23.365912,5.0,115.0,Credit Card,In-store,2023-05-11
11085,TXN_4376840,CUST_21,Computers and electric accessories,Item_14_CEA,24.500000,8.0,196.0,Digital Wallet,Online,2024-06-15
11733,TXN_8832056,CUST_22,Butchers,Item_16_BUT,27.500000,1.0,27.5,Cash,In-store,2022-10-31
2188,TXN_5611996,CUST_09,Food,Item_13_FOOD,23.000000,6.0,138.0,Cash,In-store,2024-11-07
11658,TXN_3981959,CUST_02,Milk Products,Item_1_MILK,5.000000,9.0,45.0,Credit Card,In-store,2022-04-16
10013,TXN_6182374,CUST_04,Furniture,Item_23_FUR,38.000000,5.0,190.0,Cash,In-store,2024-03-27
2916,TXN_3201198,CUST_21,Patisserie,Item_12_PAT,21.500000,2.0,43.0,Credit Card,In-store,2024-09-09
8057,TXN_5045913,CUST_01,Furniture,Item_23_FUR,38.000000,4.0,152.0,Digital Wallet,Online,2022-10-17
1445,TXN_2472483,CUST_21,Electric household essentials,Item_19_EHE,32.000000,2.0,64.0,Credit Card,Online,2022-09-18
108,TXN_9279462,CUST_25,Furniture,Item_5_FUR,11.000000,3.0,33.0,Credit Card,In-store,2022-02-05
11717,TXN_7595390,CUST_14,Butchers,Item_13_BUT,23.000000,6.0,138.0,Credit Card,In-store,2023-04-08
1008,TXN_6375978,CUST_23,Milk Products,Item_11_MILK,20.000000,10.0,200.0,Digital Wallet,In-store,2022-04-07
2313,TXN_1812590,CUST_17,Furniture,Item_25_FUR,41.000000,3.0,123.0,Cash,In-store,2023-07-23
7221,TXN_6633776,CUST_12,Beverages,Item_19_BEV,32.000000,6.0,192.0,Credit Card,In-store,2023-07-06
7249,TXN_9093693,CUST_02,Beverages,Item_16_BEV,27.500000,10.0,275.0,Cash,In-store,2022-04-18